# Generated by Django 3.2.4 on 2022-04-10 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('level', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('direction', models.CharField(max_length=100)),
                ('nameleader', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('id_course', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.course')),
            ],
            options={
                'verbose_name': 'Promo',
                'verbose_name_plural': 'Promos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PromoStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=50)),
                ('promo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.promo', verbose_name='Promo')),
            ],
            options={
                'verbose_name': 'PromoStudent',
                'verbose_name_plural': 'PromoStudents',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('bday', models.DateField()),
                ('numdoc', models.CharField(max_length=50)),
                ('blood', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('id_group', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.group')),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('bday', models.DateField()),
                ('numdoc', models.CharField(max_length=50)),
                ('blood', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('id_group', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.group')),
                ('promo', models.ManyToManyField(blank=True, through='api.PromoStudent', to='api.Promo', verbose_name='Promo')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='promostudent',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.student', verbose_name='Student'),
        ),
        migrations.AddField(
            model_name='promo',
            name='id_teacher',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.teacher'),
        ),
    ]
