# Generated by Django 3.2.4 on 2022-04-11 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promostudent',
            name='student',
            field=models.ForeignKey(default=1, blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.student', verbose_name='Student'),
        ),
    ]
